queue:
  dev: datalake-develop
  nonprod: datalake-np
  prod:

steps:
  - step: docker-build-and-push
    stage_name: 'DEV'
    branches: 'feature/* defect/*'
    properties:
      env:
        CONFIG: dev

  - step: docker-build-and-push
    stage_name: 'NONPROD'
    branches: 'develop'
    properties:
      env:
        CONFIG: nonprod
  - wait

  - step: deploy-ecs
    stage_name: 'DEV'
    branches: 'feature/* defect/*'
    properties:
     env:
       CONFIG: dev

  - step: deploy-ecs
    stage_name: 'NONPROD'
    branches: 'develop'
    properties:
      env:
        CONFIG: nonprod
  - wait
